apiVersion: v1
kind: Pod
metadata: 
  name: mongodb
  namespace: roboshop
  labels:
    name: mongodb
    project: roboshop
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongodb
      project: roboshop
      tier: db
  template:
    metadata:
      labels:
        name: mongodb
        project: roboshop
        tier: db
    spec:    
      containers:
      - name: mongodb
        image: mongodb/gopi1214:v1
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    name: mongodb
    project: roboshop
    tier: db
  ports:
  - protocol: TCP
    port: 27017 #service-port
    targetPort: 27017 #container-port

    
